name: Release Rust Binaries

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build release binary
        run: cargo build --release

      - name: Prepare binary for upload
        run: |
          mkdir -p release
          cp target/release/spike-spy release/spike-spy-$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
